### ISSUE TITLE
Visual Studio.NET

### ISSUE THREAD

**Issue by sougay254** [ECPay/ECPayAIO_Net#1]
作者有沒有一些可以參考的作品c#
因為都沒有註解那些，看不懂如何產生超商代碼繳費那些方式!!

**Comment by AllennChang** [comment]
您好, 您的反應我會反應給開發團隊 ,整理相關sample code 提供大家使用

**Comment by AllennChang** [comment]
已提供相關範例, 若有任何問題,歡迎再跟我們反應, 謝謝您
