### ISSUE TITLE
部分程式碼 未公開.

### ISSUE THREAD

**Issue by JaySkyworker** [ECPay/ECPayAIO_Net#2]
同樣是  ECPay.Payment.Integration SDK 中介程式

PHP 版 , 公開
https://github.com/ECPay/ECPayAIO_PHP/blob/master/AioSDK/sdk/ECPay.Payment.Integration.php

JAVA 版 ,公開
https://github.com/ECPay/ECPayAIO_Java/tree/master/ecpay/payment/integration

但是 .NET 版 卻包裝成 DLL
https://github.com/ECPay/ECPayAIO_Net/blob/master/ECPay.Payment.Integration.dll
無法自由存取 程式碼

對.net 的開發人員, 相對的比較不友善, 
(DLL 綁定 asp.net 4.5, 無法開發 .net standard, .net core 相關程式）

希望這部分 程式碼 能直接公開.

**Comment by AllennChang** [comment]
您好, 感謝您的反應, 您的建議會反應給開發團隊,待討論後再回覆您結果,

**Comment by AllennChang** [comment]
＿

> 同樣是 ECPay.Payment.Integration SDK 中介程式
> 
> PHP 版 , 公開
> https://github.com/ECPay/ECPayAIO_PHP/blob/master/AioSDK/sdk/ECPay.Payment.Integration.php
> 
> JAVA 版 ,公開
> https://github.com/ECPay/ECPayAIO_Java/tree/master/ecpay/payment/integration
> 
> 但是 .NET 版 卻包裝成 DLL
> https://github.com/ECPay/ECPayAIO_Net/blob/master/ECPay.Payment.Integration.dll
> 無法自由存取 程式碼
> 
> 對.net 的開發人員, 相對的比較不友善,
> (DLL 綁定 asp.net 4.5, 無法開發 .net standard, .net core 相關程式）
> 
> 希望這部分 程式碼 能直接公開.

hi 您好. 我們已公開原始碼, 請參考 https://github.com/ECPay/ECPayAIO_Net/tree/master/ECPay.Payment.Integration
