### ISSUE TITLE
請問有.net core 版本嗎？

### ISSUE THREAD

**Issue by natelin08** [ECPay/ECPayAIO_Net#3]
目前這個套件好像不能在.net core上運行
請問有core版本嗎？
謝謝

**Comment by AllennChang** [comment]
您好，感謝您的提問，經開發團隊確認，目前sdk已支援 .Net Core，若有任何問題　歡迎再次跟我們反應，　感謝您

**Comment by Benknightdark** [comment]
您好，請問有dotnet core 的範例程式嗎

**Comment by AllennChang** [comment]
您好，感謝您的提問，很抱歉目前我們沒有.NET CORE的範例程式，若有任何問題　歡迎再次跟我們反應，　感謝您

**Comment by Benknightdark** [comment]
OK，了解，但我們團隊目前使用dotnet core串接ecpay的api，目前有碰到一個問題，等等我會開一個新ISSUE，再請您看一下，謝謝

**Comment by DillonZip** [comment]
Idk what these comments say, but if they're suggesting that this package gets updated to be supported in .Net Core then I'll give this a +1 :)

**Comment by AllennChang** [comment]
> Idk what these comments say, but if they're suggesting that this package gets updated to be supported in .Net Core then I'll give this a +1 :)

The SDK component has support for Net Core.
