### ISSUE TITLE
請問有 ASP.NET MVC 的 Sample Code 嗎？

### ISSUE THREAD

**Issue by brooke01** [ECPay/ECPayAIO_Net#4]
請問有 ASP.NET MVC 的 Sample Code 嗎？
因為這邊的 Sample Code 只有提供 ASP.NET (WebForm) 的版本而已，
希望能提供 ASP.NET MVC 的 Sample Code，謝謝。

**Comment by adelachang0418** [comment]
您好,感謝您的回饋意見
再麻煩您與我們的技術服務工程師聯絡,聯絡方式為:
techsupport@ecpay.com.tw
謝謝
