### ISSUE TITLE
如何使用dotnet core 3.1串接ECPAY api 下訂單

### ISSUE THREAD

**Issue by Benknightdark** [ECPay/ECPayAIO_Net#5]
我嘗試使用dotnet core 3.1 的HttpClient呼叫ECPAY API下訂單，雖然有成功回傳訂單的html，但是輸出到Browser時，ui的格式都會有問題
測試網址：https://fierce-falls-60746.herokuapp.com/
原始碼：https://github.com/Benknightdark/ECPAY_MVC
截圖：https://github.com/Benknightdark/ECPAY_MVC/settings
![image](https://user-images.githubusercontent.com/5799487/88517049-d20fc080-d020-11ea-80a5-d525574cd5cc.png)

**Comment by AllennChang** [comment]
您好,感謝您的提問, 請麻煩幫忙寫信到, techsupport@ecpay.com.tw ,我們將有專人幫忙協助處理您的問題,感謝
