### ISSUE TITLE
請問 checkout 用法 是否有說明？謝謝 另外 送出訂單後 可以直接取回cvs 跟 barcode 嗎？

### ISSUE THREAD

**Issue by ythsu0305-zz** [ECPay/ECPayAIO_Net#6]
請問 checkout 用法 是否有說明？謝謝 另外 送出訂單後 可以直接取回cvs 跟 barcode 嗎？

**Comment by AllennChang** [comment]
@ythsu0305  感謝您的詢問 , 回覆如下
1.      checkout用法:請參考官網API文件 (API URL:https://payment-stage.ecpay.com.tw/Cashier/AioCheckOut/V5)
2.      請參考: https://www.ecpay.com.tw/CascadeFAQ/CascadeFAQ_Qa?nID=3503

**Comment by ythsu0305-zz** [comment]
另外請問 如果單純用 C# httpPost
卻一直拿到
Error代號 10200073
因為客戶只需要抓代碼(CVS/BARCODE)
所以 只用原生的 http post
是否有合適的C# 代碼可以提供如何做checkmac 的部分?
因為文件中的加密法 似乎無法引用
順帶一提 有先對parameters 做過排序
>> dic = dic.OrderBy(o => o.Key).ToDictionary(o => o.Key, p => p.Value);
後來改用 SortedDictionary 做排序 還是獲得相同結果
再麻煩您了 感謝
![ecpay](https://user-images.githubusercontent.com/3426211/123473697-82b88280-d62b-11eb-9649-858e5e75b92a.png)

**Comment by ythsu0305** [comment]
順帶一提 有先對 parameters 做過排序 我用 dictionary

                                dic = dic.OrderBy(o => o.Key).ToDictionary(o => o.Key, p => p.Value);

**Comment by AllennChang** [comment]
> 另外請問 如果單純用 C# httpPost
> 卻一直拿到
> Error代號 10200073
> 因為客戶只需要抓代碼(CVS/BARCODE)
> 所以 只用原生的 http post
> 是否有合適的C# 代碼可以提供如何做checkmac 的部分?
> 因為文件中的加密法 似乎無法引用
> 順帶一提 有先對parameters 做過排序
> 
> > > dic = dic.OrderBy(o => o.Key).ToDictionary(o => o.Key, p => p.Value);
> > > 後來改用 SortedDictionary 做排序 還是獲得相同結果
> > > 再麻煩您了 感謝
> > > ![ecpay](https://user-images.githubusercontent.com/3426211/123473697-82b88280-d62b-11eb-9649-858e5e75b92a.png)

您好, 感謝你的回覆, 請幫忙提供相關log 記錄到, techsupport@ecpay.com.tw 客服信箱,我們會有專門的技術服務團隊協助您
