### ISSUE TITLE
ECPayAIO_Net支援.net core 8.0嗎？

### ISSUE THREAD

**Issue by jogewang** [ECPay/ECPayAIO_Net#8]
請問一下，ECPayAIO_Net支援.net core 8.0嗎？

我們有一支程式：
後端是：asp.net core 8.0(C#)開發
前端是：vue3+element UI開發
前端是透過axios-post調用後端webapi實現程式功能。

行業是：餐飲點餐系統，客人需要用手機點餐，點餐完成後，在手機上面用信用卡online結帳。

**Comment by AllennChang** [comment]
你好, 範例程式是由.NET FRamework C#開發的, 並不直接支援.net core 8.0 ,建議自行參考程式範例調整

**Comment by xqiu** [comment]
建議象paypal / stripe 等大公司的sdk一樣，提供online javascript和整合用的 dotnet package, 我們自己根據目前的API規範寫的代碼，也許過幾天由於規範的變更就不能用了。。。

**Comment by AllennChang** [comment]
您好, 目前綠界科技提供的API 都有提供向下相容的設計, 不會因為規範變更影響到廠商, 除非有法規上的強制要求, 我們也會提前公告並EMAIL通知廠商進行調整, 感謝您的詢問, 希望能有解決您的疑惑,
